version: '3.8'

services:
  blog-search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-search-engine
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python app.py
