ETL:
  downloader:
    max_workers: 4
  crawler:
    max_depth: 5
    sleep_time: 0
    max_urls_per_seed: 5000
  parser:
    min_word_count: 100
  heuristic_labeling:
    score_threshold: 8

models:
  embedding:
    model_name: google/embeddinggemma-300m
    batch_size: 32
    device: "cuda"
  reranker:
    model_name: Alibaba-NLP/gte-reranker-modernbert-base
search:
  method: "splade"
  top_k: 10
  rerank_k: 10
  reranker: true