ETL:
  downloader:
    max_workers: 16
  crawler:
    max_depth: 2
    sleep_time: 0
    max_urls_per_seed: 1000
  parser:
    min_word_count: 100
  heuristic_labeling:
    score_threshold: 8

models:
  embedding:
    model_name: "togethercomputer/m2-bert-80M-2k-retrieval"
    batch_size: 1
    device: "mps"