ETL:
  downloader:
    max_workers: 16
  crawler:
    max_depth: 2
    sleep_time: 0
    max_urls_per_seed: 1000
  parser:
    min_word_count: 100
  heuristic_labeling:
    score_threshold: 8

models:
  embedding:
    model_name: Qwen/Qwen3-Embedding-0.6B
    batch_size: 1
    device: "cuda"
  reranker:
    model_name: "ibm-granite/granite-embedding-reranker-english-r2"

search:
  method: "bm25"
  top_k: 20
  rerank_k: 20
  reranker: false